apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-egga
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0025-tenant/ci10t-786-0025-app/devfile-sample-egga@sha256:e2e21f7de2d47cc35ad4afbc404676785bb3b20610b1ec871623f313eefabb58
        name: my-nodejs
        resources: {}
status: {}
